### ISSUE TITLE
Switch stays focused after interaction

### ISSUE THREAD

**Issue by jensborch** [rmwc/rmwc#1316]
When clicking on a switch it stays focused after the interaction. It should work similar to https://mui.com/material-ui/react-switch/. This was also an issue in 8.x

**Comment by b-d-m-p** [comment]
Same on checkboxes. It has to do with the ripple https://rmwc.io/checkboxes

Although this seems strange, I believe this is the correct behavior. I made this codepen to demonstrate. 

https://codepen.io/b-d-m-p/pen/QWoYvam/198d94f87705aee5fe44933e69bd1df7

If you click the button, after you have finished the state is still focused until you click somewhere else. The ripple does not get applied to the object clicked as a focus would be in an html element, but it is mimicking or enhancing the normal focus behavior and because the selected element has not been unfocused, the ripple stays there. So, I think this is correct.

**Comment by b-d-m-p** [comment]
Was discussed with team. This is the correct behavior. Closing.
