### ISSUE TITLE
Process is not defined, Vite-React-RMWC

### ISSUE THREAD

**Issue by blained-dev** [rmwc/rmwc#843]
- What RMWC Version are you using [major.minor.patch]: 8.0.3

- Name your build system [Webpack, Rollup...]: Rollup

- Describe the bug with as much detail as possible: I am using Vite instead of the typical create-react-app for my project. Whenever I attempt to render a RMWC component, I get a `process is not defined` error in the console. Following this takes me to the line `export var RMWC_VERSION = process.env.RMWC_VERSION || 'rmwc_version'; `. As per Vite's docs, `process.env` is replaced with `import.meta.env` (https://vitejs.dev/guide/env-and-mode.html), and I am at a loss on how to fix this issue

- What happened, and what was supposed to happen: Components should render correctly and take into account the fact that process.env does not exist, however this does not seem to be the case.

**Comment by EmiBemi** [comment]
We actually discussed using Vite instead of create-react-app. Hopefully we will look into this migration soon!

**Comment by getsalty** [comment]
For anyone still experiencing this issue, the work around is to add this line to your `vite.config.ts` file:

```
export default defaultConfig({
  // ...
  define: {
    'process.env': {}
  }
})
```

This will give you an empty object for `process.env` and allow you to continue without error.

**Comment by getsalty** [comment]
For some information on why this is an issue.  `process.env` is a Node.js variable.  Historically, since JS has been used on frontend and backend code, the separation of variables and packages based on what type of code you are writing has become muddied.  We have seen issues arise with people trying to use backend npm packages in their frontend code (like crypto based projects).

With all that said, `process.env` is a Node.js variable - a backend variable.  The past few years, more and more frontend based projects are leaving `process.env` behind in favor of `import.meta.env`.  Webpack 5 is one of the most notable projects that dropped `process.env`.  Here is an excerpt from their official v4 to v5 Migration Guide:

---
  
![image](https://user-images.githubusercontent.com/836241/215191390-5b6b40fa-ab53-4020-b44f-44ce08388703.png)

---

Special emphasis for a couple of those bullets:
 - "webpack 5 does no longer include a polyfill for this Node.js variable. Avoid using it in the frontend code."  They explicitly say don't use it on the frontend.
 - "process.env is Node.js specific and should be avoided in frontend code."  Again, they explicitly say not to use it on the frontend.
 
 So why does CRA still work with `process.env`? From what I can find, CRA seems to ignore the recommendation and polyfill `process.env` anyway. I think they used `dotenv` and included it in the production build as well.  Since CRA builds SPAs which are entirely frontend, they should deprecate the Node.js variable, but they probably wont any time soon (if they even release an update any time soon). As you can see on this thread (https://github.com/facebook/create-react-app/issues/11756) people are not happy that they deprecated most of the Node.js variables.  So with that and the rumors about CRA development dying, chances of them deprecating `process.env` are slim.
 
 So to the contributors of RMWC, in user land this library is being used in front end products (Vite, CRA, etc) and backend products (next.js, etc). So please, if you ever push a change for environment variables, make sure that both configurations are covered or at least escape-able.

**Comment by jensborch** [comment]
@getsalty with version 14 we have migrated RMWC to Vite and removed any use of process.env so this should no longer be an issue
